version: '2'
volumes:
  jenkins-home:
    driver: ${VOLUME_DRIVER}

services:
  jenkins-ssh-slave:
    image: "jenkinsci/ssh-slave"
    ports:
      - ${PORT}:22/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: gitlab/gitlab-ce:9.5.10-ce.0
    volumes:
      - jenkins-home:/var/opt/jenkins
    environment:
      - JENKINS_AGENT_HOME=/var/opt/jenkins
      - JENKINS_SLAVE_SSH_PUBKEY="${JENKINS_SLAVE_SSH_PUBKEY}"
      