.catalog:
  name: Jenkins
  version: 2.92-rancher1
  description: |
    Jenkins SSH Slave.
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 2222
    required: true
  - variable: ""
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    default: "/var/lib/docker/jenkins-ci"
    type: "string"
jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
