.catalog:
  name: Jenkins
  version: 0.0.1
  description: |
    Jenkins SSH Slave - Add SSH slave to your Jenkins CI instance.
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 2222
    required: true
  - variable: "JENKINS_SLAVE_SSH_PUBKEY"
    description: "The public SSH that Jenkins uses to connect to this instance"
    label: "Public SSH Key"
    required: true
    type: "string"
jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
